# Generated by Django 4.1.3 on 2022-11-03 12:51

import calc.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Operation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operation_type', models.CharField(choices=[(calc.models.OperationTypes['addition'], 'addition'), (calc.models.OperationTypes['subtraction'], 'subtraction'), (calc.models.OperationTypes['multiplication'], 'multiplication')], max_length=20)),
            ],
        ),
    ]
