# Generated by Django 4.1.3 on 2022-11-03 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calc', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='operation',
            name='x',
            field=models.IntegerField(default=0, max_length=100),
        ),
        migrations.AddField(
            model_name='operation',
            name='y',
            field=models.IntegerField(default=0, max_length=100),
        ),
    ]
