# Generated by Django 4.1.3 on 2022-11-03 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calc', '0002_operation_x_operation_y'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operation',
            name='x',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='operation',
            name='y',
            field=models.IntegerField(default=0),
        ),
    ]
