# Generated by Django 4.1.3 on 2022-11-03 15:29

import calc.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calc', '0003_alter_operation_x_alter_operation_y'),
    ]

    operations = [
        migrations.CreateModel(
            name='OpResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slackUsername', models.CharField(max_length=50)),
                ('operation_type', models.CharField(choices=[(calc.models.OperationTypes['addition'], 'addition'), (calc.models.OperationTypes['subtraction'], 'subtraction'), (calc.models.OperationTypes['multiplication'], 'multiplication')], max_length=20)),
                ('result', models.IntegerField(default=0)),
            ],
        ),
    ]
