# Generated by Django 4.1.3 on 2022-11-03 15:49

import calc.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calc', '0005_remove_operation_operation_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='operation',
            name='operation_type',
            field=models.CharField(choices=[(calc.models.OperationTypes['addition'], 'addition'), (calc.models.OperationTypes['subtraction'], 'subtraction'), (calc.models.OperationTypes['multiplication'], 'multiplication')], default='addition', max_length=20),
        ),
    ]
